### PR TITLE
Add a correct implementation of ck-get-x11-server-pid for FreeBSD.

### PR DESCRIPTION
**Pull request by arrowd**
The previous implementation always returned a pid of the first Xorg process found. In case of 2 concurrent Xorg running the `ck-get-x11-server-pid` helper returned the same PID for both sessions.

### CODE REVIEW

**Comment by arrowd** [comment]
@rnagy How about making a 2.0.0 release? This would allow me to approach polkit upstream with a patch that adapts to the API breakage.

**Comment by arrowd** [comment]
Monthly ping.

**Comment by rnagy** [comment]
I am doing throughout testing with the new branch, so please give me some more time.

**Comment by arrowd** [comment]
Pinging again.

**Comment by arrowd** [comment]
Another monthly ping. If there is any way I can help with moving this forward, I'd be happy to do so.

**Comment by rnagy** [comment]
> Another monthly ping. If there is any way I can help with moving this forward, I'd be happy to do so.

I am looking into this right now. There might be a bug with seat numbering still, trying to figure that out now.

**Comment by arrowd** [comment]
Sure, but we're running this unreleased version of ConsoleKit internally at $WORK for quite a time and it seems to work for us even with ttyv > 10

**Comment by rnagy** [comment]
> Sure, but we're running this unreleased version of ConsoleKit internally at $WORK for quite a time and it seems to work for us even with ttyv > 10

In the meantime what you could do is the handle the NEWS file for the 2.0.0 release please.

**Pull request merged**
