### PR TITLE
Export Seat's CanGraphical property on the D-Bus

### PR DESCRIPTION
**Pull request by arrowd**

### CODE REVIEW

**Comment by arrowd** [comment]
@rnagy Can we get this in too?

**Comment by rnagy** [comment]
What was the use-case for this again?

**Comment by arrowd** [comment]
This is yet another compatibility shim with login1. SDDM tries to access this property for each Seat it obtains from `ListSeats`.

**Comment by rnagy** [comment]
Ah okay. I see. I still think that you can't take copyright just by adding a function to that file,
please amend the commit message to include the company sponsorship.

**Comment by arrowd** [comment]
What's wrong with adding copyrights? I'd take them out if I could, but it my company's requirement to put them anywhere I touch the code. It'd be much easier for me to contribute if I won't need to go through our lawyer each time asking her if it's OK to remove the copyright in this specific case.

**Pull request merged**
