### PR TITLE
add init support to shutdown commands

### PR DESCRIPTION
**Pull request by abchk1234**
Checks for openrc and runit via `init=/sbin/openrc-init` and `init=/sbin/runit-init` respectively.

Links:
* https://wiki.gentoo.org/wiki/Runit#Runit_as_the_init_system
* https://wiki.gentoo.org/wiki/OpenRC/openrc-init

Tested on Slackware Linux with `init=/sbin/openrc-init`

### CODE REVIEW

**Comment by abchk1234** [comment]
@fungilife if you can point me to the relevant s6 commands and test that it works, will be happy to add it!

**Comment by Obarun** [comment]
Can i ask the support of 66 with the following addition?

for the `tools/linux/ck-system-stop`

```
if [ "$(ps -p 1 -o comm=)" = runit-init ]; then
	SHUTDOWN_CMD=runit-init
	SHUTDOWN_CMD_ARGS="0"
fi

if [ "$(ps -p 1 -o comm=)" = s6-svscan ]; then
	SHUTDOWN_CMD_ARGS='-p now'
fi
```

**Comment by skarnet** [comment]
@abchk1234 Unlike openrc and runit, s6 does not enforce policy on its users (it is more flexible), so there are no "dedicated" shutdown commands; it all depends on how the distribution wants to install and use s6. So it is impossible to add generic "s6 support" without knowing more details.

However, s6 provides a sysvinit compatibility layer, `s6-linux-init`, for people who wish to use it as a full init system. In that situation, the same commands that you would use with sysvinit will also work with s6: the `shutdown`, `reboot`, `halt` and `poweroff` commands are all supported. So, if you add support for a sysvinit-style shutdown, then that backend will work with a large number of s6 installations.

**Comment by abchk1234** [comment]
@Obarun I added a case for `s6-svscan`. Let me know if it works ok.

@skarnet Thanks for your input! The default shutdown command is used in case a specific init case is not provided, so it should work correctly.

**Comment by abchk1234** [comment]
@Obarun I changed the default shutdown command arguments to `-h -P now`, hope that it works in case of 66 now.

I could not add a special case for `s6-svscan`, as according to @skarnet there is no definitive way to use s6 as init.

I could add a case like the following:
~~~~
	s6-svscan)
		SHUTDOWN_CMD=s6-linux-init-shutdown
		SHUTDOWN_CMD_ARGS="-h -P now"
	;;
~~~~
but this would fail if a user does not have `s6-linux-init` installed, but is still using s6-svscan as their init manager.

**Comment by skarnet** [comment]
@abchk1234 And in distros that do use `s6-linux-init`, then there should be links and scripts accessible in PATH and making `shutdown`, `reboot`, `poweroff` and `halt` work properly, without the `s6-linux-init-` prefix. So I don't think your special case would be useful.

**Comment by Obarun** [comment]
Your proposed change will not work for 66 as we don't use s6-linux-init.
Anyway i will patch ck-system-stop and ck-system-restart to make it work as package installation.
Thanks for your interest.

**Comment by fungilife** [comment]
1  I couldn't give a shit about improving ck2 functionality, my intention was to engage those very few people following ck development in answering this question:

"what the hell is 66?"
for some it may even be what is s6?  Not a runit fork?


2  Long conversation on movim yesterday, you may have missed it.  Some new person using obarun asked the interesting question can he move/relocate ~/.66  to another user specified directory.  I had to go back to boot-user@ module to see if there is a definition for it that can be set optional.   I thought it was an interesting relatively easy option to provide.  Have ~/.66 as default and uncomment it in the module and provide an option "within" home/user/

**Comment by ajacoutot** [comment]
Should be fixed by https://github.com/ConsoleKit2/ConsoleKit2/pull/131

**Pull request closed without merging**
