### PR TITLE
Follow logind in seat/session naming scheme.

### PR DESCRIPTION
**Pull request by arrowd**
It it took quite a bit of work but now ConsoleKit does not confuse IDs and paths.

This unfortunately may break consumers. At least Polkit is affected as it also treats IDs as paths. It can be easily patched to handle both cases, though.

Based on #142

### CODE REVIEW

**Comment by rnagy** [comment]
Hi

First of all you have conflicts here and then I think we have to take this slow. I am more than happy
to get these merged, but we need to make sure we are not breaking anything that is using ConsoleKit2.

I suggest that we break things up into small commits and go from there. Please do not make a huge pull request at once.

**Comment by arrowd** [comment]
> First of all you have conflicts here

I'll rebase this after my previous PRs get merged.

> I suggest that we break things up into small commits and go from there. Please do not make a huge pull request at once.

I'd be happy to do so, but simply replacing paths to proper IDs causes changes seat/session hashmaps and then to almost every function that uses them. Also signal emission is affected as all signals should continue emitting paths.

Unfortunately, I don't see a way to reduce the churn created by this change.

**Comment by rnagy** [comment]
> > First of all you have conflicts here
> 
> I'll rebase this after my previous PRs get merged.
> 
> > I suggest that we break things up into small commits and go from there. Please do not make a huge pull request at once.
> 
> I'd be happy to do so, but simply replacing paths to proper IDs causes changes seat/session hashmaps and then to almost every function that uses them. Also signal emission is affected as all signals should continue emitting paths.
> 
> Unfortunately, I don't see a way to reduce the churn created by this change.

Okay, let's see how it goes. I will do some extensive testing with other consolekit users and see what's needed.

**Comment by arrowd** [comment]
I have pushed this change into FreeBSD ports along with a patch for Polkit. Let's see how this would work in the wild.

**Comment by rnagy** [comment]
Please resolve conflicts for merging.

**Comment by arrowd** [comment]
Awesome, thanks for merging all the stuff!

I still have some bits pending, so it'd be nice if you don't cut a new release right away.

**Pull request merged**
